services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile_symfony
      args:
        USERNAME: username
        UID: 666
        EMAIL: nathan.nicolessi@etu.univ-orleans.fr
        NAME: "Nathan Nicolessi"
    container_name: symfony_server
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8082:8000"
    environment:
      PHP_IDE_CONFIG: serverName=symfony_server
      PS1: "[Symfony|$$(whoami)|$$(basename $$(pwd))] "
    tty: true
    stdin_open: true

  angular:
    build:
      context: .
      dockerfile: Dockerfile_angular
      args:
        USERNAME: username
        UID: 666
        EMAIL: nathan.nicolessi@etu.univ-orleans.fr
        NAME: "Nathan Nicolessi"
    container_name: angular_server
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "8081:4200"
    environment:
      PS1: "[NG|$$(whoami)|$$(basename $$(pwd))] "
    tty: true
    stdin_open: true
