FROM alpine:latest

# Arguments nécessaires
ARG USERNAME
ARG UID
ARG EMAIL
ARG NAME

# Installation de npm, nodejs et angular
RUN apk --no-cache update && \
    apk --no-cache add bash git shadow wget && \
    apk --no-cache add npm 'nodejs>20.11' && \
    npm install -g typescript && \
    npm install -g @angular/cli && \
    # Gestion user
    echo "UID_MAX 9223372036854775807" > /etc/login.defs && \
    /usr/sbin/useradd -m -s /bin/sh -u "$UID" $USERNAME

# Spécifique à l'utilisateur
USER $USERNAME
# Configuration de git
RUN git config --global user.email "$MAIL" && \
    git config --global user.name "$NAME"

WORKDIR /var/www/html
