FROM php:8.3-fpm-alpine

# Arguments nécessaires
ARG USERNAME
ARG UID
ARG EMAIL
ARG NAME

# Installation de php, composer et symfony CLI
RUN apk --no-cache update && apk --no-cache add bash git npm shadow curl; \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin && \
    php -r "unlink('composer-setup.php');" && \
    curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash; \
    apk add symfony-cli; \
    # Gestion user
    echo "UID_MAX 9223372036854775807" > /etc/login.defs && \
    /usr/sbin/useradd -m -s /bin/sh -u "$UID" $USERNAME

# Spécifique à l'utilisateur
USER $USERNAME
# Configuration de git
RUN git config --global user.email "$MAIL" && \
    git config --global user.name "$NAME"

WORKDIR /var/www/html
